import skin from "../../assest/images/skin4.jpg"
import skin1 from "../../assest/images/skin2.jpg"
import skin2 from "../../assest/images/skin3.jpg";
import skin3 from "../../assest/images/skin1.jpg";
import skin4 from "../../assest/images/skin5.jpg";
export function getBrowsingData(param) {
  return [
    {
      id: 0,
      prodimg: skin,
      prodname: "cetaphil",
      prod_detail1: "Soothing Cleanser-olay",
      prod_detail2: "Effectively and deeply cleans",
      prod_detail3: "Daily Facial Cleanser",
      prod_detail4: "cleansing thoroughly yet leaving skin soft",
      prod_detail5: "Regenerist Micro-Sculpting Cream",
      prod_detail6: "Highly hydrating",
      prod_detail7: "Dramatically Different Moisturizing Lotion",
      prod_detail8: "Powerful hydrating effects",
      price: "999/-",
      quantity: 0,
    },
    {
      id: 1,
      prodimg: skin1,
      prodname: "Skin Ceuticals",
      prod_detail1: "Skin ceutical serum ",
      prod_detail2: "Green gel - moisturiser",
      prod_detail3: "Skin ceutical serum",
      prod_detail4: "Green gel - moisturiser",
      prod_detail5: "Skin ceutical serum",
      prod_detail6: "Green gel - moisturiser",
      prod_detail7: "Skin ceutical serum",
      prod_detail8: "Green gel - moisturiser",
      price: "799/-",
      quantity: 0,
    },
    {
      id: 2,
      prodimg: skin2,
      prodname: "Smoothing gel",
      prod_detail1: "Facial scrub",
      prod_detail2: "Anti-Oxide ingredients",
      prod_detail3: "Facial scrub",
      prod_detail4: "Anti-Oxide ingredients",
      prod_detail5: "Facial scrub",
      prod_detail6: "Anti-Oxide ingredients",
      prod_detail7: "Facial scrub",
      prod_detail8: "Anti-Oxide ingredients",
      price: "899/-",
      quantity: 0,
    },
    {
      id: 3,
      prodimg: skin3,
      prodname: "Lacto calamine",
      prod_detail1: "Lacto products for all skin types",
      prod_detail2: "Lacto -calamine",
      prod_detail3: "Lacto products for all skin types",
      prod_detail4: "Lacto -calamine",
      prod_detail5: "Lacto products for all skin types",
      prod_detail6: "Lacto -calamine",
      prod_detail7: "Lacto products for all skin types",
      prod_detail8: "Lacto -calamine",
      price: "599/-",
      quantity: 0,
    },
    {
      id: 4,
      prodimg: skin4,
      prodname: "Vitaminc-serum",
      prod_detail1: "Daycream gel",
      prod_detail2: "Vitaminc products for moisturising",
      prod_detail3: "Daycream gel",
      prod_detail4: "Vitaminc products for moisturising",
      prod_detail5: "Daycream gel",
      prod_detail6: "Vitaminc products for moisturising",
      prod_detail7: "Daycream gel",
      prod_detail8: "Vitaminc products for moisturising",
      price: "699/-",
      quantity: 0,
    },
    {
      id: 5,
      prodimg: skin,
      prodname: "cetaphil",
      prod_detail1: "Soothing Cleanser-olay",
      prod_detail2: "Effectively and deeply cleans",
      prod_detail3: "Daily Facial Cleanser",
      prod_detail4: "cleansing thoroughly yet leaving skin soft",
      prod_detail5: "Regenerist Micro-Sculpting Cream",
      prod_detail6: "Highly hydrating",
      prod_detail7: "Dramatically Different Moisturizing Lotion",
      prod_detail8: "Powerful hydrating effects",
      price: "999/-",
      quantity: 0,
    },
  ];
}
